<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ERROR_CAN_NOT_UPLOAD_FILE' => 'No se pudo subir el archivo.',
    'ERROR_DURING_UPLOAD_PROCESS' => '¡Se produjo un error durante el proceso de carga!',
    'ERROR_FILE_ALREADY_EXIST' => 'Un archivo con el mismo nombre ya existe.',
    'ERROR_FILE_IDENTIFIER_MUST_BE_PROVIDED' => 'Se debe proporcionar el identificador de archivo.',
    'ERROR_FILE_DOES_NOT_EXIST' => 'El archivo especificado no existe.',
    'ERROR_CANNOT_REMOVE_FILE' => 'No se puede eliminar el archivo, algo salió mal.',
];
