<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ERROR_CAN_NOT_UPLOAD_FILE' => 'File could not be uploaded.',
    'ERROR_DURING_UPLOAD_PROCESS' => 'An error occurred during the upload process!',
    'ERROR_FILE_ALREADY_EXIST' => 'The file with such name already exist',
    'ERROR_FILE_IDENTIFIER_MUST_BE_PROVIDED' => 'File identifier must be provided.',
    'ERROR_FILE_DOES_NOT_EXIST' => 'Specified file does not exist.',
    'ERROR_CANNOT_REMOVE_FILE' => 'Cannot remove the file, something goes wrong.',
];
